[package]
name = "example"
version = "0.1.0"
authors = ["Andreas <shadowstep7@gmail.com>"]

build = "build.rs"

[lib]
crate-type=["cdylib"]

[dependencies]
tackweld = { path = "../lib" }

[build-dependencies]
tackweld-parse-templates = { path = "../parse-templates" }