[package]
authors = ["Andreas Stocker <shadowstep7@gmail.com>"]
name = "tackweld-parse-templates"
version = "0.1.0"

[dependencies]
error-chain = "0.11.0"
globset = "0.2.1"
lazy_static = "1.0.0"
regex = "0.2.3"
walkdir = "2"
